### ISSUE TITLE
SQL Search tool: Write to MyDB fails for a simple query

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#182]
Testing the new "MyDB" output option on preprod SkyServer.

For a fairly simple query of DR12 - "select top 10 \* from specobj" - the query fails with the error message

Failed to upload table data: Expected 190 column[s], found 182

Screnshot below.

I suspect that the CasJobs upload is choking on some empty columns.

Screenshot of bug:

![specobj_to_mydb_bug](https://cloud.githubusercontent.com/assets/1709156/14956552/62a0dc52-104e-11e6-85f3-6801b03cc665.png)

**Comment by mtaghiza** [comment]
This is an error produced in CasJobs,. What happens is that there are about 7 columns that might have more than 1 empty row (e.g. run1d, class_noqso, subClass_noqso, comments_person, etc).
In that case, the CSV that is created and sent to CasJobs has nothing between commas, and CasJobs' CSV parser seems not to understand that. 

Creating an issue in CasJobs instead.

**Comment by thakar** [comment]
Here "empty" means the empty string right? In any case, the CSV parser
should probably handle this but we are not going to make any changes to it,
so we'll just have to live with this bug, I think.

```
 Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

The best lack all conviction, while the worst
Are full of passionate intensity. [W. B. Yeats]

**Comment by mtaghiza** [comment]
Yes, those columns are empty strings. Thinking it better, all strings could be padded by quotation marks, and a database Null value could just be written as ...,NULL,... to make a difference with the string.

Since we also need to fix the CSV table upload through SciDrive in the future, we need to agree on which of these rules we are using, have them being consistent across all Sciserver tools and and let the users know them.

**Comment by mtaghiza** [comment]
ok, so I pushed some changes into github, so that users will get consistent outputs from skyserver.

Now database null values appear as NULL in the csv and html output formats, and strings now appear padded by double quotes in the csv output format. 
You can test this by running 

select Null as 'dd', 'ds' as 'dd2', '' as 'fe2'

in the sql search tool.

Please, test this new modification when the fixed are moved to test/prod, thanks.

**Comment by dmedv** [comment]
This should be fixed in the CasJobs CSV parser now, there is no need for changes in SkyServer.

**Comment by mtaghiza** [comment]
ok, so no need to test the changes I mentioned. We'll instead include this fixes in a release the next few weeks, which probably will include fixes to other bugs we might find on the way.

**Comment by mtaghiza** [comment]
But please, **do** test the integration with CasJobs, that is, the MyDB output option in search tools. Thanks.
