### ISSUE TITLE
"Click to Report Error" button goes to wrong bug report page on sciserver.org

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#183]
On preprod SkyServer, when a query fails to write its results in MyDB, the error page shows a "Click to Report Error" button. This button points to the site:

http://www.sciserver.org/bug-report/

Which gives a "Not Found" link.

Has the URL of the bug report form changed?

**Comment by bonbons0220** [comment]
Looks like Manu thought the new bug-report form would be ready to go for the release, but it isn't. The url for the bug report form should be http://www.sciserver.org/support/bug-report-and-suggestion-form/. Sorry for any confusion!

**Comment by raddick** [comment]
We will need to update the URL to the bug report form in all the Web.config files associated with SkyServer. Who can do this?

**Comment by dmedv** [comment]
I can. Done (on test.preprod).

**Comment by raddick** [comment]
Thanks, @dmedv! Did you update the test.preprod web.config file in Alfresco?

**Comment by bonbons0220** [comment]
You may not want to hear this, but you can probably keep the original link
to bug-report link in SkyServer etc. The reason it wasn't working before is
that Ninja Forms broke during one of their updates.

But, anyhow, you can use whichever link you want. I can always add a
redirect in the .htaccess file.

The "new' bug-report was supposed to add variable passthrough so that we
receive more information about the bug, like their casjobs username. But
Manu found some problems with it, so it's probably not strictly ready for
release.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu
