### ISSUE TITLE
DR12 SkyServer still has the SciServer orange monster

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#219]
Looks like the SciServer orange window announcing SSO and Compute never got taken off the DR12 SkyServer ... the change must not have been propagated to that version/branch (the front page says sciserver v1.8.0).

**Comment by mtaghiza** [comment]
Yes, the banner was updated in the DR13 branch, but not in the branch of DR12 (sciserver_vm). The sciserver_vm branch was never deployed again since 1.8.0 because all new functional changes in DR13 where not applicable to the DR12 version (eg: new manga section, hiding of DR13 saw links, etc). We will have to copy  the DR13 banner into the sciserver_vm branch for the next 1.8.3 release. Will also apply some new bug fixes that were discovered in DR13 since the last 1.8.2 release.

**Comment by mtaghiza** [comment]
Fixed.
