### ISSUE TITLE
SkyServer URL missing the data release keyword ('DR12')

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#41]
Ani pointed out that the SkyServer URL was incorrectly configured, that is, does not show the 'DR12' keyword (should be <baseurl/dr<n>/, where <n> is the release number ).

**Comment by raddick** [comment]
Manu (@mtaghiza) explained this issue to me - got it. Technically it's not a bug because the code as written now **will** work on the production site, even though it doesn't work on the test site for the reasons Manu explained.

Filing it as a bug anyway, because that statement makes me very uncomfortable. The point of a test environment is that we should be able to push from test to prod without making any changes to the code.

**Comment by mtaghiza** [comment]
works now under test.preprod. Please confirm and close.

**Comment by mtaghiza** [comment]
Just tested in prod version sciserver-v1.8.1. Issue is fixed. Closing issue...
